### ISSUE TITLE
使用CDM算分结果为nan

### ISSUE THREAD

**Issue by yjc11** [opendatalab/UniMERNet#26]
[{'pred': '\\begin{matrix}{=\\frac{7}{25}\\times\\frac{4}{9}+\\frac{7}{9}\\times\\frac{5}{9}\\\\ =\\frac{7}{25}\\times(\\frac{1}{9}+\\frac{5}{9})\
\\\ =\\frac{7}{25}\\times1\\\\ =\\frac{25}{7}\\times1\\\\ =\\frac{7}{7}\\\\ =\\frac{7}{7}\\end{matrix}', 'gt': '\\frac{7}{25}\\times\\frac{4}{9}+\\frac{7}{25}\\times\\frac{5}{9}\\n=\\frac{7}{25}\\time
s\\left(\\frac{4}{9}+\\frac{5}{9}\\right)\\n=\\frac{7}{25}\\times1\\n=\\frac{7}{25}'}]

ReferenceError: exit is not defined
    at parseArray (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/environments.js:26:13)
    at Object.handler (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/environments.js:190:11)
    at Parser.parseImplicitGroup (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/Parser.js:452:26)
    at Parser.parseAtom (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/Parser.js:306:21)
    at Parser.parseExpression (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/Parser.js:151:25)
    at Parser.parseInput (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/Parser.js:118:27)
    at Parser.parse (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/Parser.js:109:22)
    at parseTree (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/src/parseTree.js:14:19)
    at Object.generateParseTree [as __parse] (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/third_party/katex/katex.js:61:12)                                                            " 20:37 12-Sep-24
    at Interface.<anonymous> (/public/youjiachen/workspace/cdm-demo/modules/tokenize_latex/preprocess_formula.js:51:30)
2024-09-12 12:37:54 extract bbox done, time cost: 2.955 s
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5349.88it/s]
/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.                                                                                             " 20:37 12-Sep-24
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
2024-09-12 12:37:54 calculate metrics done, time cost: 0.003 s
=> process done, mean f1 score: nan.
=> more details of metrics are saved in `output/m2e/metrics_res.json`
=> visulization images are saved under `output/m2e/vis_match`

**Comment by wufan-tb** [comment]
json里面需要把反斜杠进行转义，参考这个文件里给的案例https://github.com/opendatalab/UniMERNet/blob/main/cdm/assets/example/input_example.json

**Comment by wangbinDL** [comment]
@yjc11 我们已经更新[README](https://github.com/opendatalab/UniMERNet/blob/main/cdm/README-CN.md)，可以重新试一下，有问题欢迎随时反馈。

**Comment by yenchyun7217** [comment]
您好！我用了你们的input_example.json，但是结果还是nan
(CDM) ysh@ubuntu:/data1/doc_data/ysh/UniMERNet/cdm$ python evaluation.py -i /data1/doc_data/ysh/UniMERNet/cdm/test.json
Namespace(input='/data1/doc_data/ysh/UniMERNet/cdm/test.json', output='output', pools=240)
collect gt latex ...: 3it [00:00, 71089.90it/s]
collect pred latex ...: 3it [00:00, 108473.38it/s]
2025-05-27 12:27:09 using processpool, pool num: 240 , job num: 6
2025-05-27 12:27:13 extract bbox done, time cost: 3.553 s
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3693.25it/s]
/home/ysh/anaconda3/envs/CDM/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ysh/anaconda3/envs/CDM/lib/python3.9/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
2025-05-27 12:27:13 calculate metrics done, time cost: 0.004 s
=> process done, mean f1 score: nan.
=> more details of metrics are saved in `output/test/metrics_res.json`
=> visulization images are saved under `output/test/vis_match`
生成的图片都是这样的

![Image](https://github.com/user-attachments/assets/801a9045-0e9e-431b-a67f-a3844f382ee0)
请问是什么问题呀
