### ISSUE TITLE
AttributeError: 'CustomMBartDecoder' object has no attribute 'embed_scale'

### ISSUE THREAD

**Issue by MathTeller** [opendatalab/UniMERNet#4]
Traceback (most recent call last):
  File "/root/autodl-tmp/UniMERNet/demo.py", line 64, in <module>
    latex_code = processor.process_single_image(image_path)
  File "/root/autodl-tmp/UniMERNet/demo.py", line 45, in process_single_image
    output = self.model.generate({"image": image})
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/unimernet/models/unimernet/unimernet.py", line 80, in generate
    outputs = self.model.generate(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 746, in generate
    outputs = self.model.generate(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/transformers/generation/utils.py", line 2397, in _sample
    outputs = self(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 618, in forward
    decoder_outputs = self.decoder(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 483, in forward
    outputs = self.model.decoder(
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 235, in forward
    inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale
  File "/root/miniconda3/envs/unimernet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CustomMBartDecoder' object has no attribute 'embed_scale'

**Comment by wangbinDL** [comment]
Hi, @MathTeller 

Thanks for pointing that out. The issue is caused by a version mismatch with the `transformers` library. Please downgrade to version 4.40.0 by running the following commands:

```bash
pip uninstall transformers
pip install transformers==4.40.0
```

We've updated `unimernet` to require this specific version of `transformers` to prevent similar issues in the future.
